Algoritmo "calculadora"

Var
   // Seção de Declarações das variáveis
   numeroA: inteiro
   numeroB: inteiro
   resultado: real
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   //este codigo faz uma soma
   //escreval("Informe um número inteiro:")
   leia(numeroA)
   escreval("Informe outro número inteiro:")
   leia(numeroB)
   resultado <- numeroA + numeroB
   escreval("O resultado é:", resultado)
Fimalgoritmo